name: Production Deployment

on:
  workflow_run:
    workflows:
      - Development Build
    types:
      - completed

jobs:
  approve-and-deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Request approval to deploy
        run: echo "Please manually trigger this job for production deployment."

      - name: Await manual approval
        uses: peter-evans/workflow-dispatch@v1
        with:
          workflow: 'deploy.yml'  # Adjust to the name of the deploy workflow file
          ref: refs/heads/main    # Specify the branch to use for triggering the deployment
          
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: production-artifact

      - name: Deploy to production
        run: |
          echo "Deploying to production..."
          # Add your deployment commands here
