name: Production Deployment

on:
  workflow_run:
    workflows:
      - Development Build
    types:
      - completed

jobs:
  approve-and-deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    environment:
      name: production  # This step will pause for approval

    # steps:
    #   - name: Download artifact
    #     uses: actions/download-artifact@v3
    #     with:
    #       name: production-artifact

      - name: Deploy to production
        run: |
          echo "Deploying to production..."
          # Your deployment commands here
